name: exception
description: "A Flutter package module for standardized exception handling and error management in Flutter applications."
version: 0.0.5
homepage: 'https://github.com/KB-FMF/flutter-package-core.git'

environment:
  sdk: ^3.7.0
  flutter: '>=3.3.0'

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  dio: 5.8.0+1
  json_annotation: 4.9.0
  hive_ce: 2.10.1
  hive_ce_flutter: 2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0
  json_serializable: 6.9.4
  build_runner: 2.4.15
  hive_ce_generator: 1.8.2
