name: storage
description: "Provides local storage utilities and secure data persistence using Hive CE and Flutter Secure Storage for Flutter applications"
version: 0.0.5
homepage: 'https://github.com/KB-FMF/flutter-package-core.git'
publish_to: 'none'

environment:
  sdk: ^3.7.0
  flutter: '>=3.3.0'

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  hive_ce: 2.10.1
  hive_ce_flutter: 2.2.0
  get_it: 8.0.3
  flutter_secure_storage: 9.2.4
  exception:
    path: ../exception

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0
  build_runner: 2.4.15
  hive_ce_generator: 1.8.2
