name: network
description: "Core networking module providing secure communication, HTTP request handling, response serialization, API interceptors and logging capabilities for Flutter applications."
version: 0.0.5
homepage: 'https://github.com/KB-FMF/flutter-package-core.git'
publish_to: 'none'

environment:
  sdk: ^3.6.1
  flutter: '>=3.27.3'

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  dio: 5.8.0+1
  get_it: 8.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0
